### ISSUE TITLE
Visual Studio Product Group Feedback (Snowball) - Visual Studio Credential authentication flow

### ISSUE THREAD

**Issue by TravisFallsMSFT** [retaildevcrews/ngsa-asb#153]
**Description** 

- Create Snowball entry for Visual Studio credential flow issue
  - Create a document that details the experience when using DefaultAzureCredential and Visual Studio Auth.  
- Look within the repository for defects presenting in the same fashion. 
  - Contact any PG contacts to inquire AFTER looking at the repository
- Reach out the DLs for Visual Studio 

**Conditions of Satisfaction**

- Successfully create a snowball entry for the PG
- Document findings for other research gathering activities and submit the research to the working group.

**Comment by TravisFallsMSFT** [comment]
Create a document that illustrates the issues with having multiple tenants and using DefaultAzureCredential to authenticate.  Once created and approved, enter into snowball.

**Comment by jofultz** [comment]
The entry has been created: [Set Tenant Priority in VS2022 for use with DefaultCredential](https://dev.azure.com/unifiedactiontracker/Technical%20Feedback/_workitems/edit/147671?src=WorkItemMention&src-action=artifact_link)
